# -*- coding: utf-8 -*-
"""tugas5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lY_Dyt4X-nSqqjk1cQk0VGMgWxFVeNop
"""

# Inisialisasi list untuk menyimpan nilai siswa
nilai_siswa = []

# Input nilai untuk 5 siswa
for i in range(5):
    nilai = float(input(f"Masukkan nilai siswa ke-{i+1}: "))
    nilai_siswa.append(nilai)

# Menentukan nilai tertinggi dan posisi siswa
nilai_tertinggi = max(nilai_siswa)
posisi_siswa = nilai_siswa.index(nilai_tertinggi) + 1  # Indeks dimulai dari 0, jadi ditambah 1

# Menampilkan hasil
print(f"\nNilai tertinggi: {nilai_tertinggi}")
print(f"Siswa ke-{posisi_siswa} mendapat nilai tertinggi.")