# -*- coding: utf-8 -*-
"""tugas3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lY_Dyt4X-nSqqjk1cQk0VGMgWxFVeNop
"""

# Input harga dan jumlah barang
harga_barang1 = float(input("Masukkan harga barang 1: Rp"))
jumlah_barang1 = int(input("Masukkan jumlah barang 1: "))
harga_barang2 = float(input("Masukkan harga barang 2: Rp"))
jumlah_barang2 = int(input("Masukkan jumlah barang 2: "))
harga_barang3 = float(input("Masukkan harga barang 3: Rp"))
jumlah_barang3 = int(input("Masukkan jumlah barang 3: "))

# Hitung total harga per barang
total_barang1 = harga_barang1 * jumlah_barang1
total_barang2 = harga_barang2 * jumlah_barang2
total_barang3 = harga_barang3 * jumlah_barang3

# Hitung total keseluruhan
total_pembayaran = total_barang1 + total_barang2 + total_barang3

# Tampilkan hasil
print("\n===== Rincian Pembelian =====")
print(f"Barang 1: {jumlah_barang1} x Rp{harga_barang1} = Rp{total_barang1}")
print(f"Barang 2: {jumlah_barang2} x Rp{harga_barang2} = Rp{total_barang2}")
print(f"Barang 3: {jumlah_barang3} x Rp{harga_barang3} = Rp{total_barang3}")
print(f"Total Pembayaran: Rp{total_pembayaran}")