# -*- coding: utf-8 -*-
"""tugas1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lY_Dyt4X-nSqqjk1cQk0VGMgWxFVeNop
"""

# Input total belanja dari pengguna
total_belanja = float(input("Masukkan total belanja Anda: Rp"))

# Inisialisasi variabel diskon
diskon = 0

# Logika pemberian diskon
if total_belanja >= 500000:
    diskon = total_belanja * 0.1
    print("Selamat! Anda mendapatkan diskon 10%")
else:
    print("Tidak ada diskon")

# Menghitung total bayar setelah diskon
total_bayar = total_belanja - diskon

# Menampilkan hasil
print(f"Total belanja Anda: Rp{total_belanja:,.0f}")
print(f"Diskon: Rp{diskon:,.0f}")
print(f"Total yang harus dibayar: Rp{total_bayar:,.0f}")