# -*- coding: utf-8 -*-
"""tugas4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lY_Dyt4X-nSqqjk1cQk0VGMgWxFVeNop
"""

def faktorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * faktorial(n - 1)

angka = int(input("Masukkan angka untuk dihitung faktorialnya: "))
if angka < 0:
    print("Faktorial tidak didefinisikan untuk angka negatif.")
else:
    print(f"Faktorial dari {angka} adalah {faktorial(angka)}")