# -*- coding: utf-8 -*-
"""tugas2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lY_Dyt4X-nSqqjk1cQk0VGMgWxFVeNop
"""

# Input nilai ujian dari pengguna
nilai_matematika = float(input("Masukkan nilai Matematika: "))
nilai_bahasa_indonesia = float(input("Masukkan nilai Bahasa Indonesia: "))
nilai_ipa = float(input("Masukkan nilai IPA: "))

# Menghitung rata-rata nilai
rata_rata = (nilai_matematika + nilai_bahasa_indonesia + nilai_ipa) / 3

# Menampilkan hasil
print(f"\nRata-rata nilai: {rata_rata:.2f}")

# Menentukan status kelulusan
if rata_rata >= 75:
    print("Status: Lulus")
else:
    print("Status: Tidak Lulus")